[tool.isort]
profile = "black"
import_heading_stdlib = "Stdlib"
import_heading_firstparty = "First Party"
import_heading_thirdparty = "Third Party"
import_heading_localfolder = "Local"

[tool.mypy]
disallow_untyped_defs = true
ignore_missing_imports = true
no_implicit_optional = true
show_error_context = true
show_column_numbers = true
warn_return_any = true
warn_unused_ignores = true
warn_redundant_casts = true
